MOST_PROBABLY_EN = 'Most probably'
PROBABLY_EN = 'Probably'
SMALL_CHANCE_EN = 'Small chance that'
ACTION_EN = 'Action'
MOST_PROBABLY_UA = 'Швидше за все'
PROBABLY_UA = 'Ймовірно'
SMALL_CHANCE_UA = 'Невеликий шанс, що'
ACTION_UA = 'Дії'